"use client";

import React, { useState, useEffect } from "react";
import Link from "next/link";
import { Terminal, Code, Award, Check, X, ShieldAlert, Sparkles, RefreshCw, Bookmark } from "lucide-react";
import { motion as m, AnimatePresence } from "framer-motion";

const CODING_HISTORY = [
  {
    era: "1843",
    title: "The First Computer Algorithm",
    pioneer: "Ada Lovelace",
    details: "Ada Lovelace translated Italian mathematician Luigi Menabrea's memoir on Charles Babbage's proposed Mechanical Engine. In her notes, she appended an algorithm to compute Bernoulli numbers, widely recognized today as the first complex computer program.",
    impact: "First to realize that computers could express more than just quantities, laying the groundwork for symbolic programming."
  },
  {
    era: "1952",
    title: "The Compiler is Born",
    pioneer: "Grace Hopper",
    details: "Grace Hopper designed the A-0 compiler system, which translated mathematical code instructions into machine-readable binary. When told computers could only do arithmetic, she persisted, creating compiler tools that led directly to COBOL.",
    impact: "Established the concept of high-level programming languages that humans can write and computers compile."
  },
  {
    era: "1972",
    title: "C Language & System Engineering",
    pioneer: "Dennis Ritchie",
    details: "Developed at Bell Labs by Dennis Ritchie, the C language was built to rewrite the Unix operating system. It provided low-level memory control with high-level readability, forming the foundation of modern OS code.",
    impact: "Remains the most influential programming language of all time, serving as the foundation of C++, Java, C#, and JavaScript."
  },
  {
    era: "1995",
    title: "JavaScript Rules the Web",
    pioneer: "Brendan Eich",
    details: "Brendan Eich created JavaScript in just 10 days while working at Netscape Communications. It was designed to add dynamic scripts to static HTML documents inside the Netscape Navigator browser.",
    impact: "Evolved from a simple scripting language to the dominant language of web application frontends and server-side nodes."
  }
];

const SYNTAX_PUZZLES = [
  {
    id: "sp-1",
    language: "JavaScript",
    code: `const obj = {
  value: 42,
  getValue: function() {
    return () => this.value;
  }
};
const retrieve = obj.getValue();
console.log(retrieve());`,
    question: "What will this JavaScript code output to the console?",
    options: ["42", "undefined", "ReferenceError", "null"],
    answer: 0,
    explanation: "Arrow functions do not bind their own 'this'. Instead, they capture the 'this' value of the enclosing lexical context. Here, 'this' refers to the obj context, returning 42."
  },
  {
    id: "sp-2",
    language: "Python",
    code: `lst = [1, 2, 3]
new_lst = lst
new_lst.append(4)
print(len(lst))`,
    question: "What is the length of the original list 'lst'?",
    options: ["3", "4", "AttributeError", "0"],
    answer: 1,
    explanation: "In Python, lists are mutable objects. Assigning 'new_lst = lst' creates a reference pointing to the same list memory slot. Mutating 'new_lst' also mutates 'lst'."
  },
  {
    id: "sp-3",
    language: "SQL",
    code: `SELECT COUNT(*) 
FROM Users 
WHERE Age > 18 
GROUP BY Country 
HAVING COUNT(*) > 10;`,
    question: "Which keyword executes filter conditions on grouped records in SQL?",
    options: ["WHERE", "HAVING", "GROUP BY", "SELECT"],
    answer: 1,
    explanation: "The WHERE clause filters individual row records before grouping, while the HAVING clause filters groups generated by GROUP BY."
  }
];

const CHEAT_SHEETS = [
  {
    title: "Flexbox Alignment Cheat Sheet",
    category: "CSS Layout",
    items: [
      { key: "display: flex", value: "Initiates flex container context." },
      { key: "flex-direction: row | column", value: "Sets primary layout axis." },
      { key: "justify-content", value: "Aligns flex items along the main axis (e.g. center, space-between)." },
      { key: "align-items", value: "Aligns flex items along the cross axis (e.g. center, stretch)." }
    ]
  },
  {
    title: "Git Essentials Cheat Sheet",
    category: "Version Control",
    items: [
      { key: "git add .", value: "Stages all modified project files." },
      { key: "git commit -m 'msg'", value: "Records current workspace snapshot." },
      { key: "git push origin branch", value: "Sends local commits to online remote repository." },
      { key: "git pull origin branch", value: "Fetches and integrates remote changes." }
    ]
  },
  {
    title: "SQL Joins Summary Cheat Sheet",
    category: "Databases",
    items: [
      { key: "INNER JOIN", value: "Returns matching records in both tables." },
      { key: "LEFT JOIN", value: "Returns all records from left table, plus matched right table records." },
      { key: "RIGHT JOIN", value: "Returns all records from right table, plus matched left table records." },
      { key: "FULL JOIN", value: "Returns all records when there is a match in either left or right." }
    ]
  }
];

export default function CodingPage() {
  const [puzzleAnswer, setPuzzleAnswer] = useState<number | null>(null);
  const [showExplanation, setShowExplanation] = useState(false);

  // Date-based rotators
  const getDayIndex = () => {
    if (typeof window === "undefined") return 0;
    const now = new Date();
    const start = new Date(now.getFullYear(), 0, 0);
    const diff = now.getTime() - start.getTime();
    const oneDay = 1000 * 60 * 60 * 24;
    return Math.floor(diff / oneDay);
  };

  const dayIdx = getDayIndex();
  const history = CODING_HISTORY[dayIdx % CODING_HISTORY.length];
  const puzzle = SYNTAX_PUZZLES[dayIdx % SYNTAX_PUZZLES.length];
  const cheatSheet = CHEAT_SHEETS[dayIdx % CHEAT_SHEETS.length];

  // Solve callback
  const handleSelectOption = (idx: number) => {
    if (puzzleAnswer !== null) return;
    setPuzzleAnswer(idx);
    setShowExplanation(true);
    
    // Grant XP if correct
    if (idx === puzzle.answer) {
      const currentXp = parseInt(localStorage.getItem("ilm_v2_xp") || "350");
      const currentLvl = parseInt(localStorage.getItem("ilm_v2_level") || "1");
      let nextXp = currentXp + 100; // 100 XP for coding challenge
      let nextLvl = currentLvl;
      if (nextXp >= 1000) {
        nextXp -= 1000;
        nextLvl += 1;
        localStorage.setItem("ilm_v2_level", nextLvl.toString());
      }
      localStorage.setItem("ilm_v2_xp", nextXp.toString());
    }
  };

  const handleResetPuzzle = () => {
    setPuzzleAnswer(null);
    setShowExplanation(false);
  };

  return (
    <div className="flex-1 min-h-screen flex flex-col pb-36 bg-background text-foreground transition-all duration-300 font-sans">
      
      {/* Standardized Header */}
      <header className="sticky top-0 z-40 w-full border-b border-border bg-background/80 backdrop-blur-md">
        <div className="max-w-xl mx-auto px-4 h-16 flex items-center justify-between">
          <span className="font-serif text-2xl font-extrabold tracking-tight">Ilm.</span>
          <div className="flex items-center gap-4">
            <div className="flex items-center gap-3 text-[11px] font-bold uppercase tracking-widest text-muted-foreground">
              <Link href="/about" className="hover:text-foreground transition-colors">About</Link>
              <Link href="/contact" className="hover:text-foreground transition-colors">Contact</Link>
            </div>
          </div>
        </div>
      </header>

      {/* Main content body */}
      <main className="flex-1 max-w-xl w-full mx-auto px-4 py-8 flex flex-col gap-6">
        
        {/* Milestone: History of Coding */}
        <div className="rounded-xl border border-border bg-card p-6 shadow-sm">
          <div className="flex items-center justify-between pb-3.5 border-b border-border/40 mb-4">
            <span className="text-[9px] font-bold text-muted-foreground uppercase tracking-wider">
              Coding History Milestone · Era {history.era}
            </span>
            <span className="text-xs font-bold text-primary">{history.pioneer}</span>
          </div>

          <h2 className="text-xl font-extrabold font-serif tracking-tight mb-2">
            {history.title}
          </h2>
          <p className="text-xs sm:text-sm leading-relaxed text-foreground/95 mb-4">
            {history.details}
          </p>

          <div className="p-3 bg-secondary/50 rounded-lg border border-border/50 text-xs">
            <span className="font-bold text-[9px] text-muted-foreground uppercase tracking-widest block mb-1">Impact</span>
            <p className="font-semibold text-foreground">{history.impact}</p>
          </div>
        </div>

        {/* Challenge: Syntax Puzzle */}
        <div className="rounded-xl border border-border bg-card p-6 shadow-sm flex flex-col gap-4">
          <div className="flex items-center justify-between pb-2 border-b border-border/40">
            <span className="text-xs font-bold text-muted-foreground uppercase flex items-center gap-1.5">
              <Code className="h-4 w-4 text-primary" /> Syntax Challenge
            </span>
            {puzzleAnswer !== null && (
              <button 
                onClick={handleResetPuzzle}
                className="text-[10px] font-bold text-muted-foreground hover:text-primary flex items-center gap-1"
              >
                <RefreshCw className="h-3 w-3" /> Reset
              </button>
            )}
          </div>

          <h3 className="text-xs sm:text-sm font-bold text-foreground leading-snug">
            {puzzle.question}
          </h3>

          {/* Code block preview */}
          <pre className="p-4 rounded-lg bg-secondary/70 border border-border/70 text-xs font-mono overflow-x-auto text-foreground select-none leading-relaxed">
            <code>{puzzle.code}</code>
          </pre>

          {/* Multi-choice options */}
          <div className="flex flex-col gap-2.5">
            {puzzle.options.map((opt, idx) => {
              const isCorrect = idx === puzzle.answer;
              const isSelected = puzzleAnswer === idx;
              const hasSelected = puzzleAnswer !== null;

              let buttonStyles = "border-border hover:bg-secondary/40";
              if (hasSelected) {
                if (isCorrect) {
                  buttonStyles = "bg-green-500/10 border-green-500 text-green-700 dark:text-green-400";
                } else if (isSelected) {
                  buttonStyles = "bg-red-500/10 border-red-500 text-red-700 dark:text-red-400";
                } else {
                  buttonStyles = "opacity-50 border-border";
                }
              }

              return (
                <button
                  key={idx}
                  onClick={() => handleSelectOption(idx)}
                  disabled={hasSelected}
                  className={`w-full text-left p-3.5 text-xs sm:text-sm font-semibold rounded-lg border transition-all flex items-center justify-between ${buttonStyles}`}
                >
                  <span>{opt}</span>
                  {hasSelected && isCorrect && <Check className="h-4 w-4 text-green-600 dark:text-green-400 shrink-0" />}
                  {hasSelected && isSelected && !isCorrect && <X className="h-4 w-4 text-red-600 dark:text-red-400 shrink-0" />}
                </button>
              );
            })}
          </div>

          <AnimatePresence>
            {showExplanation && (
              <m.div
                initial={{ opacity: 0, height: 0 }}
                animate={{ opacity: 1, height: "auto" }}
                className="p-3 bg-secondary/40 rounded border border-border/50 text-[11px] leading-relaxed mt-1"
              >
                <span className="font-bold block text-muted-foreground uppercase text-[9px] mb-1">Explanation</span>
                {puzzle.explanation}
              </m.div>
            )}
          </AnimatePresence>
        </div>

        {/* Cheat Sheet: Dev Cheat Sheet */}
        <div className="rounded-xl border border-border bg-card p-6 shadow-sm">
          <div className="flex items-center justify-between pb-3.5 border-b border-border/40 mb-4">
            <span className="text-[9px] font-bold text-muted-foreground uppercase tracking-wider">
              {cheatSheet.category} · Cheat Sheet
            </span>
            <span className="text-xs font-bold text-primary">{cheatSheet.title}</span>
          </div>

          <div className="flex flex-col gap-3">
            {cheatSheet.items.map((item, idx) => (
              <div key={idx} className="flex justify-between items-baseline text-xs gap-4 py-1.5 border-b border-border/40 last:border-b-0">
                <span className="font-mono font-bold text-primary text-[11px] shrink-0 bg-secondary px-1.5 py-0.5 rounded border border-border/30">
                  {item.key}
                </span>
                <span className="text-muted-foreground font-semibold text-right">{item.value}</span>
              </div>
            ))}
          </div>
        </div>

      </main>



    </div>
  );
}
